services:
  qc.sec_sleepy-zucchini-ant:
    command: sleep 6000000
    image: secfigo/bandit
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_gimpy-charcoal-oriole:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sty/pycodestyle
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
